### ISSUE TITLE
Doesn't work for MCPE Players

### ISSUE THREAD

**Issue by OfficialLilKev** [Shelly7w7/VoucherPlus#1]
The plugin doesn't work on MCPE

**Comment by OfficialLilKev** [comment]
Only works for Windows 10 Players

**Comment by Shelly7w7** [comment]
I'm pretty sure, in New update, you need to tap/hold in air for a longer amount of time.

**Comment by Shelly7w7** [comment]
It works for me, can you reproduce it?

**Comment by Shelly7w7** [comment]
Never received a reply, closing.
